### ISSUE TITLE
Timeslot/program schedule issue - unable to create specials

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#10]
We have a custom Drupal 7 module which works in conjunction with a shell script based in cron to schedule audio recordings that are then attached to nodes in Drupal based on certain criteria. There are timeslots for each program episode, and the script auto-creates episodes in advance of the program's timeslot. But if there is a manually created special program, it should override the auto-created episode. This is the part that is currently not working in the script. The manually-created episode does not override the auto-created one, and timeslots that differ from the existing program are unable to be created.

**Comment by beefman1** [comment]
I made the check only look prospectively on dev because it was failing on the node we tried last night due to a month long special from this summer.  Try this and see whether it looks right to you on dev.  See http://xdev.kboo.fm/47510-timeslot-news-depth for an example, where i excluded next thursday's show.

**Comment by troff** [comment]
yeah that looks right. any way to get the error to display more information than just 'there is already a timeslot scheduled at that time'?
thanks

**Comment by troff** [comment]
thanks @beefman1 for fixing it :1st_place_medal:
