### ISSUE TITLE
Spinitron playlists are not showing up

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#11]
expected behavior:
playlists pulled from Spinitron API display on program episode page

current behavior: no playlists showing up as of about August 1st
(apparently some earlier ones are showing up - looks like March 2016 and earlier? ie:
http://kboo.fm/media/45393-noontime-jamboree-030716 )

modules: radio_spinitron
Spinitron playlist is displayed in the node template for station content nodes, using the start and end time of the episode to query Spinitron.
calls to Spinitron api are wrapped in the custom class 'Spinitron'Displayed in a table for all but tiny screens, then in a list group

**Comment by JohnKellermann** [comment]
Has this been fixed, or patched? Or are volunteers entering the playlists manually?

I posted this morning's show on spinitron:
http://spinitron.com/radio/playlist.php?station=kboo&month=Sep&year=2016&playlist=14882

And it showed up on the recent playlists page:
http://kboo.fm/program/playlists

But not on my program page:
http://kboo.fm/program/pastures-plenty

Or today's page:
http://kboo.fm/media/52530-pastures-plenty-091416

My playlist showed up (eventually) for the show I did last month, subbing for Kurt (after I'd added a comment linking to the playlist on spinitron) in table format, below the audio link (where it belongs):
http://kboo.fm/media/51637-lark-morning-080516

The playlist showed up on my July show page, but it looks like someone pasted in the spinitron playlist manually:
http://kboo.fm/media/51105-pastures-plenty-071316

Looks like someone pasted a playlist table into last week's show page:
http://kboo.fm/media/52385-pastures-plenty-090716

I copied today's playlist from spinitron into today's page, then saw the playlist in table format below the audio link when I viewed the page. So I deleted the spintron playlist (as redundant) and the table playlist disappeared!

Huh? How did that happen? Did my editing the page delete an auto-generated playlist?

I went back and added a link to the spinitron playlist, but the link only works on the today's page
http://kboo.fm/media/52530-pastures-plenty-091416

not on the program page:
http://kboo.fm/program/pastures-plenty

**Comment by beefman1** [comment]
Ok, this has two facets.

1) sometimes the initial query by date (Spinitron::getPlaylistsByDate) was returning a false cache hit from the file cache in sites/default/files/spinitron/cache.  To produce this, load one program in one window with a given air date.  Then load another in a different window with a different air date.  The load of the second will get a return of the first query, ie the playlist from the first date, at least until SpinitronClient::queryNoCache runs & overwrites the cached file.  Reason for this is the key computation algorithm was coming up with "ps" for the filename...  It is supposed to generate it based on the query parameters and generate a unique key.  But ps doesn't distinguish between "10/6" and "10/1".  So i added a key/value pair to the SpinitronClient spParams array that covers EndDate (the query parameter in use for the initial query).  Thus:

```
root@rose:/var/www/vhosts/dev.kboo.fm/web/sites/all/modules/custom/utilities/radio_station/lib/utilities# git diff ./SpinitronClient.inc 
diff --git a/web/sites/all/modules/custom/utilities/radio_station/lib/utilities/SpinitronClient.inc b/web/sites/all/modules/custom/utilities/radio_station/lib/utilities/SpinitronClient.inc
index c6388f2..9a2318e 100644
--- a/web/sites/all/modules/custom/utilities/radio_station/lib/utilities/SpinitronClient.inc
+++ b/web/sites/all/modules/custom/utilities/radio_station/lib/utilities/SpinitronClient.inc
@@ -154,6 +154,7 @@ class SpinPapiClient
             'StartHour' => 'h',
             'UserID' => 'u',
             'Num' => 'n',
+            'EndDate' => 'e',
         );
     }
```

So now the keys are properly generated and will not generate false file cache hits there.  To move live, i only need to commit this file change & delete the "ps" file in sites/default/files/spinitron/cache on live.

2) Second problem is that sometimes the query response comes through with the correct date, but does not include any elements that match the show's air times.  Is this an expected possible outcome?  Expected or not, it happens, eg with http://xdev.kboo.fm/media/53000-african-american-male-school-adaptability-crisis where the program airs Thu, 10/06/2016 - 11:30am to 12:00pm, but the query response has 4 programs in it, but none matching that time slot.  I left debugging code in so you can see the result on dev on that program's page.

I am not closing this yet due to #2, but i will commit the cache fix change.

Darin

**Comment by beefman1** [comment]
A followup to the above, #2.  It appears that there are no programs in that timeslot, 11:30am-12:00pm.  http://spinitron.com/radio/playlist.php?station=kboo&month=Oct&year=2016&day=06#here

So it is correctly showing nothing.

**Comment by troff** [comment]
So, here's some more info on the expected behavior:
Playlist query should include airtime of the program episode - ie. not just the date and program name should match, but also the airtime.
Music programs are on at the following times:
weekdays noon to 4 pm
weekday 8 pm to 7 am
saturday and sunday: all times - from 8 pm Friday to 7 am Monday.

Shows in other timeslots are extremely unlikely to post playlists.

So in answer to #2 - it should definitely not display a playlist for that timeslot (as it is a public affairs show) - but not sure why there is a query being submitted at all for that episode. Are playlist queries submitted for every episode, regardless of whether they are music or public affairs?

One other, separate thing that we have noticed, but this may involve a fix outside of the playlist function:
-Podcast programs, which are on the 'BooTwo' stream, are currently web-only and do not have timeslots associated with them (although this is a planned future future, as we develop our second stream). But when hosts publish episodes for podcasts on the 'BooTwo' stream, they are currently required  to include an arbitrary time and date in order for the episode to show up on their program page. When they do so, however, the playlist for the program scheduled for that same date and time on 'KBOO Stream 1' appears on the episode. 
Example:
http://kboo.fm/media/16628-19-oct-2014-1907
displays the playlist from Heavy Metal Vomit Party - because the host put the 'air date and time' of 10/23/14 at midnight.
http://spinitron.com/radio/playlist.php?station=kboo&month=Oct&year=2014&playlist=5494#here

**Comment by troff** [comment]
Q: Does the API from Spinitron allow it to pull the twitter share button and/or the 'buy it now' link? Or are those not part of the API....

**Comment by beefman1** [comment]
It queries in two steps.  First is by date, then by timeslot.  It queries for all episodes.

On the other issue: yes that makes sense.  Because it queries by date, then by time, it never confirms show name. The air date is optional now, so they could leave that blanks, or I could set it to not fetch the playlist on podcast programs.  How do you want to record that an episode is a podcast episode?

**Comment by beefman1** [comment]
I don't see anything in the spin api docs about social media links.  My guess is though that those links can be easily generated from some fetchable ID.  Can you show me one of the current twitter or buy now buttons?

**Comment by beefman1** [comment]
Ok i added code to prevent the playlist from rendering when viewing an episode produced for a program whose stream is set to bootwo.  That's live.
